# Manual enumeration of chapter titles that can't be automatically retrieved.
1 = "Ryomen Sukuna"
2 = "Secret Execution"
3 = "For Myself"
4 = "Girl of Steel"
5 = "Start"
6 = "Fearsome Womb"
7 = "Fearsome Womb, Part 2"
8 = "Fearsome Womb, Part 3"
9 = "Fearsome Womb, Part 4"
10 = "After the Rain"
11 = "A Dream"
12 = "Pushing Forward"
13 = "Watching Movies"
14 = "Assault"
15 = "Domain"
16 = "Affection"
17 = "Boring"
18 = "Bottom"
19 = "Young Fish and Reverse Punishment"
20 = "Young Fish and Reverse Punishment, Part 2"
21 = "Young Fish and Reverse Punishment, Part 3"
22 = "Young Fish and Reverse Punishment, Part 4"
23 = "Young Fish and Reverse Punishment, Part 5"
24 = "Young Fish and Reverse Punishment, Part 6"
25 = "Narrow-Minded"
26 = "To You Someday"
27 = "What If"
28 = "I'm Gonna Kill You!"
29 = "Growth"
30 = "Selfishness"
31 = "Tomorrow"
32 = "Introspection"
33 = "Kyoto Sister School Goodwill Event - Team Battle, Part 0"
34 = "Kyoto Sister School Goodwill Event - Team Battle, Part 1"
35 = "Kyoto Sister School Goodwill Event - Team Battle, Part 2"
36 = "Kyoto Sister School Goodwill Event - Team Battle, Part 3"
37 = "Kyoto Sister School Goodwill Event - Team Battle, Part 4"
38 = "Kyoto Sister School Goodwill Event - Team Battle, Part 5"
39 = "Kyoto Sister School Goodwill Event - Team Battle, Part 6"
40 = "Kyoto Sister School Goodwill Event - Team Battle, Part 7"
41 = "Kyoto Sister School Goodwill Event - Team Battle, Part 8"
42 = "Kyoto Sister School Goodwill Event - Team Battle, Part 9"
43 = "Kyoto Sister School Goodwill Event - Team Battle, Part 10"
44 = "Kyoto Sister School Goodwill Event - Team Battle, Part 11"
45 = "Sage"
46 = "Time"
47 = "Cursed Tools"
48 = "Black Flash"
49 = "Constrained"
50 = "Feeling"
51 = "A Flower Offering"
52 = "Nonstandard"
53 = "Completion"
54 = "Jujutsu Koshien"
55 = "The Origin of Obedience"
56 = "The Origin of Obedience, Part 2"
57 = "The Origin of Obedience, Part 3"
58 = "The Origin of Obedience, Part 4"
59 = "The Origin of Obedience, Part 5"
60 = "The Origin of Obedience, Part 6"
61 = "The Origin of Obedience, Part 7"
62 = "The Origin of Obedience, Part 8"
63 = "Accomplices"
64 = "It's Like That"
65 = "Hidden Inventory"
66 = "Hidden Inventory, Part 2"
67 = "Hidden Inventory, Part 3"
68 = "Hidden Inventory, Part 4"
69 = "Hidden Inventory, Part 5"
70 = "Hidden Inventory, Part 6"
71 = "Hidden Inventory, Part 7"
72 = "Hidden Inventory, Part 8"
73 = "Hidden Inventory, Part 9"
74 = "Hidden Inventory, Part 10"
75 = "Hidden Inventory, Part 11"
76 = "Premature Death"
77 = "Premature Death, Part 2"
78 = "Premature Death, Part 3"
79 = "A Taste of Things to Come"
80 = "Evening Festival"
81 = "Evening Festival, Part 2"
82 = "Evening Festival, Part 3"
83 = "The Shibuya Incident, Part 1"
84 = "The Shibuya Incident, Part 2"
85 = "The Shibuya Incident, Part 3"
86 = "The Shibuya Incident, Part 4"
87 = "The Shibuya Incident, Part 5"
88 = "The Shibuya Incident, Part 6"
89 = "The Shibuya Incident, Part 7"
90 = "The Shibuya Incident, Part 8"
91 = "The Shibuya Incident, Part 9"
92 = "The Shibuya Incident, Part 10"
93 = "The Shibuya Incident, Part 11"
94 = "The Shibuya Incident, Part 12"
95 = "The Shibuya Incident, Part 13"
96 = "The Shibuya Incident, Part 14"
97 = "The Shibuya Incident, Part 15"
98 = "The Shibuya Incident, Part 16"
99 = "The Shibuya Incident, Part 17"
100 = "The Shibuya Incident, Part 18"
101 = "The Shibuya Incident, Part 19"
102 = "The Shibuya Incident, Part 20"
103 = "The Shibuya Incident, Part 21"
104 = "The Shibuya Incident, Part 22"
105 = "The Shibuya Incident, Part 23"
106 = "The Shibuya Incident, Part 24"
107 = "The Shibuya Incident, Part 25"
108 = "The Shibuya Incident, Part 26"
109 = "The Shibuya Incident, Part 27"
110 = "The Shibuya Incident, Part 28"
111 = "The Shibuya Incident, Part 29"
112 = "The Shibuya Incident, Part 30"
113 = "The Shibuya Incident, Part 31"
114 = "The Shibuya Incident, Part 32"
115 = "The Shibuya Incident, Part 33"
116 = "The Shibuya Incident, Part 34"
117 = "The Shibuya Incident, Part 35"
118 = "The Shibuya Incident, Part 36"
119 = "The Shibuya Incident, Part 37"
120 = "The Shibuya Incident, Part 38"
121 = "The Shibuya Incident, Part 39"
122 = "The Shibuya Incident, Part 40"
123 = "The Shibuya Incident, Part 41"
124 = "The Shibuya Incident, Part 42"
125 = "A Story About that Girl"
126 = "The Shibuya Incident, Part 43"
127 = "The Shibuya Incident, Part 44"
128 = "The Shibuya Incident, Part 45"
129 = "The Shibuya Incident, Part 46"
130 = "The Shibuya Incident, Part 47"
131 = "The Shibuya Incident, Part 48"
132 = "The Shibuya Incident, Part 49"
133 = "The Shibuya Incident, Part 50"
134 = "The Shibuya Incident, Part 51"
135 = "The Shibuya Incident, Part 52"
136 = "The Shibuya Incident, Part 53"
137 = "Hard and White"
138 = "The Zenin Clan"
139 = "Hunter"
140 = "Execution"
141 = "The Front of The Back"
142 = "A Big Brother's Back"
143 = "One More Time"
144 = "That Place"
145 = "The Back"
146 = "About the Culling Game"
147 = "Even Pandas"